-- Optional development data only. Never loaded into a remote production project automatically.
insert into public.reports(id,title,description,category,severity,ai_summary,ai_reasoning,analysis_source,area,area_key,status,risk_score,related_count,is_demo,created_at)
values
('10000000-0000-4000-8000-000000000001','Large pothole near Main Gate','Fictional demo report: a deep pothole affects people crossing the road.','road_damage','critical','Demo: a large pothole affects access.','Seeded example, not a real AI assessment. A human inspector should verify the issue.','mock','University Main Gate','university main gate','reported',75,1,true,now()),
('10000000-0000-4000-8000-000000000002','Broken streetlights near Library','Fictional demo report: the walkway lights are broken near the library.','streetlight','high','Demo: broken lights reduce visibility.','Seeded example, not a real AI assessment. Poor visibility may affect evening access.','mock','Central Library','central library','under_review',65,1,true,now()),
('10000000-0000-4000-8000-000000000003','Water leakage near Student Hall','Fictional demo report: a pipe is leaking across the walkway near the hall.','water_leakage','high','Demo: water is leaking across the walkway.','Seeded example, not a real AI assessment. An on-site review is required.','mock','Student Hall','student hall','in_progress',65,1,true,now()),
('10000000-0000-4000-8000-000000000004','Overflowing garbage near cafeteria','Fictional demo report: waste is overflowing beside the cafeteria entrance.','garbage','medium','Demo: overflowing waste requires collection.','Seeded example, not a real AI assessment. Confirm the condition with facility staff.','mock','Cafeteria','cafeteria','reported',50,1,true,now()),
('10000000-0000-4000-8000-000000000005','Drainage repair at academic building','Fictional demo report: blocked drainage at the academic building has been repaired.','drainage','low','Demo: this drainage issue has been resolved.','Seeded example, not a real AI assessment. Resolution is fictional for this demonstration.','mock','Academic Building','academic building','resolved',35,1,true,now())
on conflict(id) do nothing;
